### ISSUE TITLE
Token capacity of places in base petri net

### ISSUE THREAD

**Issue by sim-o-n** [pmlab/pmlab-lite#1]
How to deal with transitions which are enabled but their output places do not have enough capacity for a new token? Right now, this will not be checked and the transition can fire anyway.

**Comment by josepcarmona** [comment]
Hi Simon,
to me, the best would be; fire the transition, and warn about some capacities exceeded. It may then be meaningful to have a flag in the internal state of the Petri net with this. In some applications, even if the capacity is exceeded, the warning and flags can be ignored.

**Comment by glennDittmann** [comment]
As Josep proposed, the transition will now fire and put a token also into all places that are already "full".
Furthermore a warning is printied, giving insight on which place with which capacity is exceeded by how many token.

Lastly petri nets now contain a class variable holding all indexes of places that are exceeded so far. 
This includes adding them when token are put above capacity or firing a consecutive transition would reduce the number of token on the given place at or below the allowed capacity.
